### ISSUE TITLE
Invariant Violation: requireNativeComponent: "ExJitsiMeetView" was not found in the UIManager.

### ISSUE THREAD

**Issue by JijoBose** [ExentriqLtd/react-native-ex-jitsi-meet#1]
Hi, @Larens94 
I've been using this repo for my "Jitsi Meet" application in React Native.

I would like to know, what would be the replacement for "ExJitsiMeetView" since we don't have this file in the `android/src/main/java/com/reactnativejitsimeet `

```
const ExJitsiMeetView = requireNativeComponent('ExJitsiMeetView');
```
https://github.com/ExentriqLtd/react-native-ex-jitsi-meet/blob/3b0c0d2dc16c12d0c7a44b0ae7e743adf4a17233/index.android.js#LL7C49-L7C64

Thanks 😊

**Comment by Larens94** [comment]
hi this repository is under development.

I was also wrong to put it public, as soon as it's finished I'll put it public somewhere. maybe it can be of use to someone.
